spring.application.name=Revisao2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/Revisao2
spring.datasource.username=root
spring.datasource.password=